# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.3'
use_frameworks!

def testing_pods
    pod "CleverTap-iOS-SDK"
    pod 'Toast-Swift', '~> 1.1.0'
end

target 'DwindleDating' do
testing_pods
end

target 'DevDwindleDating' do
testing_pods
end
 


